#!/usr/bin/python3

import requests
import json
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime

historical_italy = "https://corona.lmao.ninja/v2/historical/italy"
historical_us = "https://corona.lmao.ninja/v2/historical/usa"

data_raw = requests.get(historical_us)
d = (data_raw.json())

db = {}
date_list = []
count_list = []

#Format data 
for date, number in d['timeline']['cases'].items():
    date = datetime.strptime(date, "%m/%d/%y").isoformat().split("T")[0]
    db[date] = int(number)
    
#create the lisy for X and Y axix
for date in sorted(db):
    date_list.append(date)
    count_list.append(db[date])

#strip the year for better formatting
date_list = [d[5:] for d in date_list]

#Plot the graph
plt.plot(date_list, count_list, color='red')
plt.title('Progression of COVID19 Cases in USA (Logarithmic Scale)')
plt.setp(plt.xticks([x for x in date_list[::2]], rotation=30, ha="right"))
plt.yscale('log')
plt.legend(['Confirmed Cases'], loc='upper left')
plt.show()
